/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface MastraAiSpans {
  attributes: Json | null;
  createdAt: Timestamp;
  createdAtZ: Generated<Timestamp | null>;
  endedAt: Timestamp | null;
  endedAtZ: Generated<Timestamp | null>;
  error: Json | null;
  input: Json | null;
  isEvent: boolean;
  links: Json | null;
  metadata: Json | null;
  name: string;
  output: Json | null;
  parentSpanId: string | null;
  scope: Json | null;
  spanId: string;
  spanType: string;
  startedAt: Timestamp;
  startedAtZ: Generated<Timestamp | null>;
  traceId: string;
  updatedAt: Timestamp | null;
  updatedAtZ: Generated<Timestamp | null>;
}

export interface MastraEvals {
  agent_name: string;
  created_at: Timestamp;
  created_atZ: Generated<Timestamp | null>;
  createdAt: Timestamp | null;
  createdAtZ: Generated<Timestamp | null>;
  global_run_id: string;
  input: string;
  instructions: string;
  metric_name: string;
  output: string;
  result: Json;
  run_id: string;
  test_info: Json | null;
}

export interface MastraMessages {
  content: string;
  createdAt: Timestamp;
  createdAtZ: Generated<Timestamp | null>;
  id: string;
  resourceId: string | null;
  role: string;
  thread_id: string;
  type: string;
}

export interface MastraResources {
  createdAt: Timestamp;
  createdAtZ: Generated<Timestamp | null>;
  id: string;
  metadata: Json | null;
  updatedAt: Timestamp;
  updatedAtZ: Generated<Timestamp | null>;
  workingMemory: string | null;
}

export interface MastraScorers {
  additionalContext: Json | null;
  analyzePrompt: string | null;
  analyzeStepResult: Json | null;
  createdAt: Timestamp;
  createdAtZ: Generated<Timestamp | null>;
  entity: Json | null;
  entityId: string | null;
  entityType: string | null;
  extractPrompt: string | null;
  extractStepResult: Json | null;
  generateReasonPrompt: string | null;
  generateScorePrompt: string | null;
  id: string;
  input: Json;
  metadata: Json | null;
  output: Json;
  preprocessPrompt: string | null;
  preprocessStepResult: Json | null;
  reason: string | null;
  reasonPrompt: string | null;
  resourceId: string | null;
  runId: string;
  runtimeContext: Json | null;
  score: number;
  scorer: Json;
  scorerId: string;
  source: string;
  spanId: string | null;
  threadId: string | null;
  traceId: string | null;
  updatedAt: Timestamp;
  updatedAtZ: Generated<Timestamp | null>;
}

export interface MastraThreads {
  createdAt: Timestamp;
  createdAtZ: Generated<Timestamp | null>;
  id: string;
  metadata: string | null;
  resourceId: string;
  title: string;
  updatedAt: Timestamp;
  updatedAtZ: Generated<Timestamp | null>;
}

export interface MastraTraces {
  attributes: Json | null;
  createdAt: Timestamp;
  createdAtZ: Generated<Timestamp | null>;
  endTime: Int8;
  events: Json | null;
  id: string;
  kind: number;
  links: Json | null;
  name: string;
  other: string | null;
  parentSpanId: string | null;
  scope: string;
  startTime: Int8;
  status: Json | null;
  traceId: string;
}

export interface MastraWorkflowSnapshot {
  createdAt: Timestamp;
  createdAtZ: Generated<Timestamp | null>;
  resourceId: string | null;
  run_id: string;
  snapshot: string;
  updatedAt: Timestamp;
  updatedAtZ: Generated<Timestamp | null>;
  workflow_name: string;
}

export interface User {
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<string>;
  name: string;
}

export interface DB {
  mastra_ai_spans: MastraAiSpans;
  mastra_evals: MastraEvals;
  mastra_messages: MastraMessages;
  mastra_resources: MastraResources;
  mastra_scorers: MastraScorers;
  mastra_threads: MastraThreads;
  mastra_traces: MastraTraces;
  mastra_workflow_snapshot: MastraWorkflowSnapshot;
  user: User;
}
