/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type PgbossJobState = "active" | "cancelled" | "completed" | "created" | "failed" | "retry";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface PgbossJob {
  completed_on: Timestamp | null;
  created_on: Generated<Timestamp>;
  data: Json | null;
  dead_letter: string | null;
  deletion_seconds: Generated<number>;
  expire_seconds: Generated<number>;
  id: Generated<string>;
  keep_until: Generated<Timestamp>;
  name: string;
  output: Json | null;
  policy: string | null;
  priority: Generated<number>;
  retry_backoff: Generated<boolean>;
  retry_count: Generated<number>;
  retry_delay: Generated<number>;
  retry_delay_max: number | null;
  retry_limit: Generated<number>;
  singleton_key: string | null;
  singleton_on: Timestamp | null;
  start_after: Generated<Timestamp>;
  started_on: Timestamp | null;
  state: Generated<PgbossJobState>;
}

export interface PgbossQueue {
  active_count: Generated<number>;
  created_on: Generated<Timestamp>;
  dead_letter: string | null;
  deferred_count: Generated<number>;
  deletion_seconds: number;
  expire_seconds: number;
  maintain_on: Timestamp | null;
  monitor_on: Timestamp | null;
  name: string;
  partition: boolean;
  policy: string;
  queued_count: Generated<number>;
  retention_seconds: number;
  retry_backoff: boolean;
  retry_delay: number;
  retry_delay_max: number | null;
  retry_limit: number;
  singletons_active: string[] | null;
  table_name: string;
  total_count: Generated<number>;
  updated_on: Generated<Timestamp>;
  warning_queued: Generated<number>;
}

export interface PgbossSchedule {
  created_on: Generated<Timestamp>;
  cron: string;
  data: Json | null;
  key: Generated<string>;
  name: string;
  options: Json | null;
  timezone: string | null;
  updated_on: Generated<Timestamp>;
}

export interface PgbossSubscription {
  created_on: Generated<Timestamp>;
  event: string;
  name: string;
  updated_on: Generated<Timestamp>;
}

export interface PgbossVersion {
  cron_on: Timestamp | null;
  version: number;
}

export interface User {
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<string>;
  name: string;
}

export interface DB {
  "pgboss.job": PgbossJob;
  "pgboss.queue": PgbossQueue;
  "pgboss.schedule": PgbossSchedule;
  "pgboss.subscription": PgbossSubscription;
  "pgboss.version": PgbossVersion;
  user: User;
}
